[package]
name = "stacks-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
bip39 = "2.1.0"
cbc = {version = "0.1.2", features = ["std"]}
pbkdf2 = "0.12.2"
rand = "0.8.5"
sha2 = "0.10.8"
aes = "0.8.4"
hmac = "0.12.1"
hex = "0.4.3"
